config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'users#index'
  # get 'users/index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index new create show destroy] do
      resources :comments, only: %i[create destroy]
      resources :likes, only: [:create]
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(current_user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all

    can :read, Post, public: true

    return unless current_user.present?

    can :manage, Post, user: current_user
    can :manage, Comment, user: current_user
    can :manage, Like, user: current_user

    return unless current_user.role == 'admin'

    can :manage, :all

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  after_save :update_comments_counter
  after_destroy :update_comments_counter

  private

  def update_comments_counter
    post.update(CommentsCounter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  after_save :update_likes_counter

  private

  def update_likes_counter
    post.update(LikesCounter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :update_posts_counter
  after_initialize :init_comments
  after_initialize :init_likes
  after_destroy :update_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :CommentsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :LikesCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def init_comments
    return unless new_record?

    self.CommentsCounter = 0
  end

  def init_likes
    return unless new_record?

    self.LikesCounter = 0
  end

  def update_posts_counter
    user.update(posts_counter: user.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'user_id', dependent: :destroy
  has_many :comments, foreign_key: 'user_id', dependent: :destroy
  has_many :likes, foreign_key: 'user_id', dependent: :destroy

  after_initialize :init

  validates :name, presence: true, length: { maximum: 30, too_long: 'Maximun for lenght is 30 char' }
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  private

  def init
    return unless new_record?

    self.posts_counter = 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email bio photo password])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[name email bio photo password current_password])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(params.require(:comment).permit(:text))
    @comment.user_id = current_user.id
    @comment.post_id = params[:post_id]

    if @comment.save
      redirect_to user_post_path(params[:user_id], params[:post_id])
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to user_posts_path
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @like = Like.new
    @like.user_id = current_user.id
    @like.post_id = params[:post_id]

    if @like.save
      redirect_to user_post_path(@user, @post)
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to user_post_path(user_id: current_user.id, id: @post.id)
    else
      render :new
    end
  end

  def destroy
    find_post
    @post.destroy
    redirect_to user_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_with model: Comment, url: user_post_comments_path(@user, @post), class: "create-comment-form" do |form| %>
  <div>
    <%= form.text_field :text, class: "create-comment-text", placeholder: "Add new comment" %>
  </div>
  <div>
    <%= form.submit "Submit", class: "create-comment-button" %><br>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Williams Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <nav>
      <ul>
        <li>The Williams Blog</li>
        <li><button type="button"> <%= link_to root_path do %>
              HOME
            <% end %></button></li>
        <% if signed_in? %>
          <li>  <%= link_to new_user_post_path(current_user.id) do %>
              <button type="button" class="create-new-post-button">Create new post</button>
            <% end %></li>
          <li><%= button_to "LOG-OUT" , destroy_user_session_path, method: :delete, data: { turbo: false }, :class => 'logout'%></li>
          <li>Your account: <%=current_user.name%></li>
        <% end %>
      </ul>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <footer>
      <h3>Developed by Williams Colmenares, all rights reserved. 2022</h3>
    </footer>
  </body>
</html>

app/views/likes/_button.html.erb
<%= form_with model: Like, url: user_post_likes_path(@user, @post), class: "like-form" do |form| %>
    <div>
      <%= form.submit "LIKE ME!", class: "likes-form" %><br>
    </div>
<% end %>

app/views/likes/_likes_button.html.erb
<%= form_with model: Like, url: user_post_likes_path(@user, @post), class: "like-form" do |form| %>
    <div>
      <%= form.submit "LIKE ME!", class: "likes-form" %><br>
    </div>
<% end %>

app/views/posts/index.html.erb
<h1>Posts endpoint</h1>
<p>Here should be displayed the users's posts</p>
<main>
  <section>
    <%= link_to "Back", user_path(@user)%>
    <div class="user-posts-card">
      <div class="user-posts-img-div">
        <img src="<%= @user.photo %>" class="user-img">
      </div>
      <div class="user-posts-info">
        <h2>
          <%= @user.name %>
        </h2>
        <span>
          Number of posts: <%= @user.posts_counter %>
        </span>
      </div>
    </div>
    <% @user.posts.each do |post| %>
      <div class="user-posts-post">
        <h2><%= link_to post.title, user_post_path(@user, post)%></h2>
        <p><%= post.text %></p>
        <span>Comments: <%= post.CommentsCounter %></span>
        <span>Likes: <%= post.LikesCounter %></span>
      </div>
      <div class="user-posts-post-comments">
        <% post.recent_comments.includes([:user]).each do |comment| %>
          <div class="single-user-single-post-single-comment">
            <p><%= comment.user.name %>: <%= comment.text %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </section>
</main>

app/views/posts/new.html.erb
<section>
  <h1>Create a New Post</h1>
  <%= form_with model: Post, url: user_posts_url do |form|%>
    <div>
      <%= form.label :title%>
      <%= form.text_field :title%>
    </div>
    <div>
      <%= form.label :text%>
      <%= form.text_field :text%>
    </div>
    <div>
      <%= form.submit "Create Post" %><br>
    </div>
  <%end%>
</section>

app/views/posts/show.html.erb
<h1>Posts endpoint</h1>
<p>Here should be displayed the users selected post</p>
<main>
  <section>
    <%= link_to "Back", user_posts_path , :class => "link-pages" %>
    <div>
      <div class="user-posts-post">
        <% if can? :destroy, @post %>
          <%= button_to "Delete this Post", user_post_path(@user, @post), method: :delete, data: { turbo_confirm: "Are you sure to delete" } %>
        <% end %>
        <h3><%= @post.title %> by: <%= @post.user.name%></h3>
        <p><%= @post.text %></p>
        <span>Comments: <%= @post.CommentsCounter %></span>
        <span>Likes: <%= @post.LikesCounter %></span>
        <%= render "likes/button" %>
      </div>
      <div class="user-posts-post-comments">
        <% @post.comments.includes(:user).each do |comment| %>
          <div class="single-user-single-post-single-comment">
            <p><strong><%= comment.user.name %>: <%= comment.text %></strong></p>
          </div>
          <%if can? :destroy , comment%>
            <%= link_to "Delete Comment" ,  user_post_comment_path(@user, @post, comment), data: { turbo_method: "delete", turbo_confirm: "Are you sure to delete" } ,class: "no-underline red-color margin"%>
          <%end%>
        <% end %>
      </div>
      <%= render "comments/form" %>
    </div>
  </section>
</main>

app/views/users/index.html.erb
<section>
  <h1>Users endpoint</h1>
  <p>Here should be displayed a list of the users</p>
  <div class='user-card-container'><% @users.each do |user|%>
      <article class='user-card'>
        <div class='user-img-div'>
          <img src=<%=user.photo%> alt='user-photo' class='user-img'>
        </div>
        <div class='user-info'>
          <h2> <%= link_to user.name, user_path(user)%></h2>
          <h3>Number of Posts: <%=user.posts_counter%></h3>
        </div>
      </article>
    <%end%>
  </div>
</section>

app/views/users/show.html.erb
<h1>Users endpoint</h1>
<p>Here should be displayed the selected user information</p>
<section>
  <%= link_to "Back", users_path(@users)%>
  <div class="user-card">
    <div class="user-img-div">
      <img src="<%= @user.photo %>" class='user-img'>
    </div>
    <div class="user-info">
      <h2>
        <%= @user.name %>
      </h2>
      <h3>
        Number of posts: <%= @user.posts_counter %>
      </h3>
    </div>
  </div>
  <div class="user-bio">
    <h3>
      Bio
    </h3>
    <p>
      <%= @user.bio %>
    </p>
  </div>
  <% @user.recent_posts.each do |post| %>
    <div class="user-post">
      <h2><%= link_to post.title, user_post_path(@user, post)%></h2>
      <p><%= post.text %></p>
      <span>Comments: <%= post.CommentsCounter %></span>
      <span>Likes: <%= post.LikesCounter %></span>
    </div>
  <% end %>
  <%= link_to user_posts_path(@user) do %>
    <button type="button" class="see-all-posts-button">See all posts</button>
  <% end %>
  <section>